module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'chore',
        'style',
        'build',
        'docs',
        'refactor',
        'revert', 
        'test',
        'ci',
        'perf',
        'release',
        'hotfix',
        'project', 
        'merge', 
        'web',
        'backend', 
        'desktop',
        'mobile',
      ],
    ],
  },
};
