version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: docs-ai
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: docs-ai
    ports:
      - '5432:5432'
volumes:
  postgres_data: